server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api #路由前缀
  retryable: true #开启重试机制
  routes:
    item-service: /item/**  # 商品微服务的映射路径
    search-service: /search/** # 搜索微服务
    user-service: /user/** # 用户微服务
    auth-service: /auth/** # 授权中心微服务
    cart-service: /cart/** #购物车
    ignored-services: upload-servie
  sensitive-headers:
  add-host-header: true #携带请求本身的头信息
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 7000
ribbon:
  ConnectTimeout: 500
  ReadTimeout: 5000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
ly:
  jwt:
    pubKeyPath: D:\item\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item

