server:
  port: 8081
spring:
  cloud:
    refresh:
      refreshable: none
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: admin
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: ly.item.exchange
    #publisher-confirms：生产者确认机制，确保消息会正确发送，如果发送失败会有错误回执，从而触发重试
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
