server:
  port: 8084
spring:
  application:
    name: goods-page
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: leyou
    password: leyou
    virtual-host: /leyou
  thymeleaf:
    cache: false
    #suffix: .html
    #prefix: classpath:/templates/
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}.${server.port}